# ---------- #

- name: Check that rootfs sfs exists
  stat:
    path: /var/tmp/sfs/rootfs.img
  register: stat_result

- name: Rootfs to squashfs
  include_role:
    name: rootfs-to-sfs
  when: not stat_result.stat.exists

- name: Create /srv/pxe
  file:
    path: /srv/pxe
    state: directory
    mode: '0755'

- name: Set preparation facts
  set_fact:
    target_path: "/srv/pxe/{{ setup_facts.setup.distro|default('devops-linux')|lower }}{{ ([''] + setup_facts.setup.shell_options)|join('-')|lower }}{{ ([''] + setup_facts.setup.ansible_options)|difference(['pxe-image','tar-image'])|join('-')|lower }}.img"

- name: "Move /var/tmp/sfs/rootfs.img to {{ target_path }}"
  command:
    cmd: "mv /var/tmp/sfs/rootfs.img {{ target_path | quote }}"
    removes: /var/tmp/sfs/rootfs.img
    creates: "{{ target_path }}"
