- name: DevOps Linux Stage 2
  hosts: all
  gather_facts: true
  strategy: free
  pre_tasks:
    - name: Prepare
      include_role:
        name: build
        tasks_from: prepare
  tasks:
    - name: Print ansible facts
      debug:
        var: ansible_facts
        verbosity: 2
    - name: Print setup config
      debug:
        var: setup_facts
        verbosity: 2
    - name: Proxmox
      include_role:
        name: proxmox
        tasks_from: stage-2
      when:
        - ('proxmox' in setup_facts.setup.ansible_options)
        - ansible_facts["distribution"] in ['Debian']
  post_tasks:
    - name: Harden kernel and system
      include_role:
        name: harden
      when: ('harden' in setup_facts.setup.ansible_options)
    - name: Audit kernel and system
      include_role:
        name: audit
      when: ('audit' in setup_facts.setup.ansible_options)
    - name: Rootfs to tar
      include_role:
        name: rootfs-to-tar
      when: >-
        ('tar-image' in setup_facts.setup.ansible_options)
    - name: Wrapup
      include_role:
        name: build
        tasks_from: wrapup
