- name: DevOps Linux Stage 1
  hosts: all
  gather_facts: true
  strategy: free
  pre_tasks:
    - name: Prepare
      include_role:
        name: build
        tasks_from: prepare
  tasks:
    - name: Print ansible facts
      debug:
        var: ansible_facts
        verbosity: 2
    - name: Print setup config
      debug:
        var: setup_facts
        verbosity: 2
    - name: Bootstrapping the initial base
      block:
        - name: First boot
          include_role:
            name: firstboot
        - name: Graphical base
          include_role:
            name: graphical-base
          when: (setup_facts.setup.ansible_options | intersect(['graphical-base', 'kde', 'cosmic', 'proxmox'])) | length > 0
        - name: LDAP Client
          include_role:
            name: ldap-auth
          when: ('ldap-auth' in setup_facts.setup.ansible_options)
    - name: Proxmox
      include_role:
        name: proxmox
        tasks_from: stage-1
      when:
        - ('proxmox' in setup_facts.setup.ansible_options)
        - ansible_facts["distribution"] in ['Debian']
  post_tasks:
    - name: Wrapup
      include_role:
        name: build
        tasks_from: wrapup
