- name: DevOps Linux Stage 2
  hosts: all
  gather_facts: true
  strategy: free
  pre_tasks:
    - name: Prepare
      include_role:
        name: build
        tasks_from: prepare
  tasks:
    - name: Print ansible facts
      debug:
        var: ansible_facts
        verbosity: 2
    - name: Print setup config
      debug:
        var: setup_facts
        verbosity: 2
    - name: Proxmox
      include_role:
        name: proxmox
        tasks_from: stage-2
      when:
        - ('proxmox' in setup_facts.setup.ansible_options)
        - ansible_facts["distribution"] in ['Debian']
    - name: KDE desktop
      include_role:
        name: kde
      when: ('kde' in setup_facts.setup.ansible_options)
  post_tasks:
    - name: Securing the system for production use
      block:
        - name: Harden kernel and system
          include_role:
            name: harden
          when: ('harden' in setup_facts.setup.ansible_options)
        - name: Audit kernel and system
          include_role:
            name: audit
          when: ('audit' in setup_facts.setup.ansible_options)
    - name: System is ready for imaging
      block:
        - name: Create tar image
          include_role:
            name: tar-image
          when: >-
            ('tar-image' in setup_facts.setup.ansible_options)
        - name: Create pxe image
          include_role:
            name: pxe-image
          when: >-
            ('pxe-image' in setup_facts.setup.ansible_options)
        - name: Create archiso image
          include_role:
            name: archiso-image
          when: >-
            ('archiso' in setup_facts.setup.ansible_options)
        - name: Create debiso image
          include_role:
            name: debiso-image
          when: >-
            ('debiso' in setup_facts.setup.ansible_options)
    - name: Wrapup
      include_role:
        name: build
        tasks_from: wrapup
