- name: DevOps Linux Stage 1
  hosts: all
  gather_facts: true
  strategy: free
  pre_tasks:
    - name: Prepare
      include_role:
        name: build
        tasks_from: prepare
  tasks:
    - name: Print ansible facts
      debug:
        var: ansible_facts
        verbosity: 2
    - name: Print setup config
      debug:
        var: setup_facts
        verbosity: 2
    - name: First boot
      include_role:
        name: firstboot
    - name: LDAP Client
      include_role:
        name: ldap
      when: setup_facts.setup.ldapauth.enabled is truthy
  post_tasks:
    - name: Wrapup
      include_role:
        name: build
        tasks_from: wrapup
