- name: DevOps Linux Stage 1
  hosts: all
  gather_facts: true
  strategy: free
  pre_tasks:
    - name: <Archlinux> Install libeatmydata
      community.general.pacman:
        # unsafe way, remember to perform a full system upgrade afterwards
        update_cache: true
        name: libeatmydata
        state: present
      when: ansible_facts["distribution"] in ['Archlinux']
    - name: <Debian,Ubuntu> Install libeatmydata
      apt:
        update_cache: true
        name: libeatmydata1
        state: present
      when: ansible_facts["distribution"] in ['Debian', 'Ubuntu']
    - name: <Archlinux> Disable fsync system-wide
      lineinfile:
        line: /usr/lib/libeatmydata.so
        path: /etc/ld.so.preload
        state: present
        create: true
      when: ansible_facts["distribution"] in ['Archlinux']
    - name: <Debian,Ubuntu> Disable fsync system-wide
      lineinfile:
        line: /usr/lib/x86_64-linux-gnu/libeatmydata.so
        path: /etc/ld.so.preload
        state: present
        create: true
      when: ansible_facts["distribution"] in ['Debian', 'Ubuntu']
  tasks:
    - name: Print ansible facts
      debug:
        var: ansible_facts
        verbosity: 2
    - name: Print setup config
      debug:
        var: setup_facts
        verbosity: 2
    - name: First boot
      include_role:
        name: firstboot
  post_tasks:
    - name: <Archlinux> Reenable fsync system-wide
      lineinfile:
        line: /usr/lib/libeatmydata.so
        path: /etc/ld.so.preload
        state: absent
      when: ansible_facts["distribution"] in ['Archlinux']
    - name: <Debian,Ubuntu> Reenable fsync system-wide
      lineinfile:
        line: /usr/lib/x86_64-linux-gnu/libeatmydata.so
        path: /etc/ld.so.preload
        state: absent
      when: ansible_facts["distribution"] in ['Debian', 'Ubuntu']
    - name: Sync all cached data to disk(s)
      command: sync
