# ---------- #

- name: Basic system toolbelt
  apt:
    name:
      # system essentials
      ###- kernel-modules-hook // Archlinux exclusive
      - polkitd
      - curl
      - wget
      - nano
      - jq
      ###- yq // Ubuntu 22.04 is still around
      - openssh-server
      - openssh-client
      - systemd-container
      - unattended-upgrades
      - ufw
      # bash tools
      - bash-completion
      ###- ncdu // Archlinux exclusive
      ###- viu // Archlinux exclusive
      - pv
      - mc
      - ranger
      - fzf
      - moreutils
      - htop
      ###- btop // missing on Debian
      - lshw
      - util-linux
      - xkcdpass
      - cryptsetup
      - tmux
      - elinks
      # git tools
      - git
      - lazygit
      # zipping and syncing
      - zstd
      - unzip
      - p7zip
      - rsync
      # user directories
      - xdg-user-dirs
      - xdg-utils
      # snapshots
      - snapper
      ###- pacman-contrib // Archlinux exclusive
      # logging
      - syslog-ng
      - logrotate
      # manuals
      - man
      - manpages-de
      # networking
      - wireguard-tools
      - gvfs
      - gvfs-backends
      - cifs-utils
      # dev stuff
      - python3-pip
      - build-essential
      - npm
      - fd-find
      - neovim
      # agents and system tools
      - qemu-guest-agent
      - kexec-tools
    state: present

- name: Install yq with fallback (Ubuntu 22.04 fix)
  block:
    - name: Install yq via apt
      apt:
        name: yq
        state: present
  rescue:
    - name: Download yq to /usr/local/bin
      shell: |
        curl --fail --silent --location --output /tmp/yq_linux_amd64.tar.gz 'https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64.tar.gz'
        tar -xzof /tmp/yq_linux_amd64.tar.gz -C /usr/local/bin/
        mv /usr/local/bin/yq_linux_amd64 /usr/local/bin/yq
        chmod 0755 /usr/local/bin/yq

- name: Enable system services
  systemd_service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - ssh
    - ufw
    - syslog-ng
    - logrotate.timer
    - systemd-networkd
    - systemd-resolved
    # Not present on some systems, thus ignoring errors
    - systemd-homed
  ignore_errors: true

- name: Disable NetworkManager completely
  systemd_service:
    name: "{{ item }}"
    masked: true
  with_items:
    - NetworkManager
    - NetworkManager-wait-online
    - NetworkManager-dispatcher
