# ---------- #

- name: Load the keyboard layout for the current session
  shell: |
    if [ -f /usr/lib/systemd/systemd-vconsole-setup ]; then
      /usr/lib/systemd/systemd-vconsole-setup
    fi

- name: Import cloud-init logs
  shell: |
    # tee -a /cidata_log <<<":: import cloud-init logs up to this point in time" >/dev/null
    sed -e '/DEBUG/d' /var/log/cloud-init.log | tee -a /cidata_log >/dev/null

- name: Archlinux
  include_tasks: pacman-1.yml
  when: ansible_facts["distribution"] in ['Archlinux']

- name: Debian/Ubuntu
  include_tasks: apt-1.yml
  when: ansible_facts["distribution"] in ['Debian', 'Ubuntu']

- name: Disable hibernation and hybrid sleep modes
  shell: |
    cp /etc/systemd/logind.conf /etc/systemd/logind.conf.bak
    sed -i 's/^#\?HandlePowerKey=.*/HandlePowerKey=poweroff/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandlePowerKeyLongPress=.*/HandlePowerKeyLongPress=poweroff/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandleRebootKey=.*/HandleRebootKey=reboot/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandleRebootKeyLongPress=.*/HandleRebootKeyLongPress=poweroff/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandleSuspendKey=.*/HandleSuspendKey=suspend/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandleSuspendKeyLongPress=.*/HandleSuspendKeyLongPress=poweroff/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandleHibernateKey=.*/HandleHibernateKey=suspend/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandleHibernateKeyLongPress=.*/HandleHibernateKeyLongPress=poweroff/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandleLidSwitch=.*/HandleLidSwitch=suspend/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandleLidSwitchExternalPower=.*/HandleLidSwitchExternalPower=suspend/' /etc/systemd/logind.conf
    sed -i 's/^#\?HandleLidSwitchDocked=.*/HandleLidSwitchDocked=ignore/' /etc/systemd/logind.conf
    cp /etc/systemd/sleep.conf /etc/systemd/sleep.conf.bak
    sed -i 's/^#\?AllowSuspend=.*/AllowSuspend=yes/' /etc/systemd/sleep.conf
    sed -i 's/^#\?AllowHibernation=.*/AllowHibernation=no/' /etc/systemd/sleep.conf
    sed -i 's/^#\?AllowSuspendThenHibernate=.*/AllowSuspendThenHibernate=no/' /etc/systemd/sleep.conf
    sed -i 's/^#\?AllowHybridSleep=.*/AllowHybridSleep=no/' /etc/systemd/sleep.conf
    systemctl mask hibernate.target suspend-then-hibernate.target hybrid-sleep.target

- name: Create user homes on login
  shell: |
    # see https://wiki.archlinux.org/title/LDAP_authentication for more details
    if [ -f /etc/pam.d/system-login ]; then
      sed -i 's/^\(session.*pam_env.so\)/\1\nsession    required   pam_mkhomedir.so     skel=\/etc\/skel umask=0077/' /etc/pam.d/system-login
    fi

- name: Load kernel modules on startup
  shell: |
    # enable ntfs3 kernel support for read/write/repair of partitions
    echo "ntfs3" | tee /etc/modules-load.d/ntfs3.conf
    tee /etc/udev/rules.d/50-ntfs.rules <<EOF
    SUBSYSTEM=="block", ENV{ID_FS_TYPE}=="ntfs", ENV{ID_FS_TYPE}="ntfs3"
    EOF
    # enable cifs kernel support for windows shares
    echo "cifs" | tee /etc/modules-load.d/cifs.conf
    # enable sg kernel support for dvd/bluray drives
    echo "sg" | tee /etc/modules-load.d/sg.conf

- name: User first time login script
  copy:
    dest: /usr/local/bin/userlogin.sh
    mode: 0755
    content: |
      #!/usr/bin/env bash
      
      # prepare user directory
      if [[ ! -f $HOME/.ssh/id_ed25519.pub ]]; then
        echo "Generating ssh keys for user '$USER'."
        mkdir -p $HOME/.ssh
        chmod 0700 $HOME/.ssh
        ssh-keygen -t ed25519 -N "" -C "" -f $HOME/.ssh/id_ed25519
        ssh-keygen -t rsa -N "" -C "" -f $HOME/.ssh/id_rsa
        chmod 0600 $HOME/.ssh/id_ed25519 $HOME/.ssh/id_rsa
        chmod 0644 $HOME/.ssh/id_ed25519.pub $HOME/.ssh/id_rsa.pub
        eval "$(ssh-agent -s)"
        ssh-add $HOME/.ssh/id_ed25519
        ssh-add $HOME/.ssh/id_rsa
        eval "$(ssh-agent -k)"
      fi
      if [[ ! -f $HOME/.wg/$USER.key ]]; then
        echo "Generating wireguard keys for user '$USER'."
        mkdir -p $HOME/.wg
        chmod 0700 $HOME/.wg
        wg genkey | tee $HOME/.wg/$USER.key | wg pubkey > $HOME/.wg/$USER.pub
        chmod 0600 $HOME/.wg/$USER.key
        chmod 0644 $HOME/.wg/$USER.pub
      fi
      # prevent error https://github.com/kovidgoyal/kitty/issues/320
      # open terminal failed: missing or unsuitable terminal: xterm-kitty
      tee $HOME/.ssh/config <<EOX
      SetEnv TERM=screen
      EOX
      # force update font cache on first login
      fc-cache -fv

- name: Archlinux
  include_tasks: pacman-2.yml
  when: ansible_facts["distribution"] in ['Archlinux']

- name: Debian/Ubuntu
  include_tasks: apt-2.yml
  when: ansible_facts["distribution"] in ['Debian', 'Ubuntu']
