# ---------- #

- name: Basic system toolbelt
  community.general.pacman:
    name:
      # system essentials
      - kernel-modules-hook
      - polkit
      - curl
      - wget
      - nano
      - jq
      - yq
      - openssh
      ###- systemd-container // Archlinux default installation
      ###- unattended-upgrades // missing on Archlinux
      - ufw
      # bash tools
      - bash-completion
      - ncdu
      - viu
      - pv
      - mc
      - ranger
      - fzf
      - moreutils
      - htop
      - btop
      - lshw
      - util-linux
      - xkcdpass
      - cryptsetup
      - tmux
      - elinks
      # git tools
      - git
      - lazygit
      # zipping and syncing
      - zstd
      - unzip
      - p7zip
      - rsync
      # user directories
      - xdg-user-dirs
      - xdg-utils
      # snapshots
      - snapper
      - pacman-contrib
      # logging
      - syslog-ng
      - logrotate
      # manuals
      - core/man
      - man-pages-de
      # networking
      - wireguard-tools
      - gvfs
      - gvfs-smb
      - cifs-utils
      # dev stuff
      - python-pip
      - base-devel
      - npm
      - fd
      - neovim
      # agents and system tools
      - qemu-guest-agent
      - kexec-tools
      # remote administration
      - cockpit
      - sscg
      - cockpit-storaged
      - cockpit-packagekit
    state: present

- name: Enable system services
  systemd_service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - linux-modules-cleanup
    - sshd
    - ufw
    - syslog-ng@default
    - logrotate.timer
    - systemd-networkd
    - systemd-resolved
    - systemd-homed
    - cockpit.socket

- name: Disable NetworkManager completely
  systemd_service:
    name: "{{ item }}"
    masked: true
  with_items:
    - NetworkManager
    - NetworkManager-wait-online
    - NetworkManager-dispatcher
