#!/usr/bin/env bash

build() {
    map add_module iscsi_tcp iscsi_ibft libiscsi libiscsi_tcp scsi_transport_iscsi crc32c
    
    add_runscript

    add_binary iscsiadm
    add_binary iscsid
    add_binary iscsiuio

    add_file /etc/iscsi/iscsid.conf
    add_file /etc/udev/rules.d/50-iscsi.rules
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for boot via PXE and iSCSI.
HELPEOF
}
