# ---------- #

- name: Archlinux
  include_tasks: pacman.yml
  when: ansible_facts["distribution"] in ['Archlinux']

- name: Debian/Ubuntu
  include_tasks: apt.yml
  when: ansible_facts["distribution"] in ['Debian', 'Ubuntu']

- name: Enable services
  systemd_service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - cups
    - libvirtd.service
    - libvirtd.socket

- name: Create /etc/NetworkManager/conf.d
  file:
    path: /etc/NetworkManager/conf.d
    state: directory
    mode: '0755'

- name: Network manager should manage virtio devices
  copy:
    dest: /etc/NetworkManager/conf.d/10-virtio-net-managed-devices.conf
    mode: 0644
    content: |
      [devices-virtio-net-managed]
      match-device=driver:virtio_net
      managed=true

- name: Main network manager config
  copy:
    dest: /etc/NetworkManager/NetworkManager.conf
    mode: 0644
    content: |
      [main]
      plugins=ifupdown,keyfile
      dns=systemd-resolved
      
      [keyfile]
      unmanaged-devices=*,except:type:ethernet,except:type:wifi,except:type:wwan
      
      [ifupdown]
      managed=true
      
      [device]
      wifi.scan-rand-mac-address=yes

- name: First, unmask network manager for graphical environment
  systemd_service:
    name: NetworkManager
    masked: false

- name: Second, enable network manager for graphical environment
  systemd_service:
    name: NetworkManager
    enabled: true

- name: Get all interfaces
  set_fact:
    ethernet_interfaces: "{{ ansible_interfaces | select('match', '^(eth|enp|ens)') | list }}"
    wireless_interfaces: "{{ ansible_interfaces | select('match', '^(wlan|wlp|wl)') | list }}"

- name: Configure wired interfaces for network manager
  copy:
    dest: "/etc/NetworkManager/system-connections/{{ item }}.nmconnection"
    mode: 0600
    content: |
      [connection]
      id={{ item }}
      uuid={{ lookup("pipe", "uuidgen") }}
      type=ethernet
      autoconnect=true
      interface-name={{ item }}
      
      [ipv4]
      method=auto
      
      [ipv6]
      addr-gen-mode=stable-privacy
      method=auto
  loop: "{{ ethernet_interfaces }}"

- name: Configure wireless interfaces for network manager
  copy:
    dest: "/etc/NetworkManager/system-connections/{{ item }}.nmconnection"
    mode: 0600
    content: |
      [connection]
      id={{ item }}
      uuid={{ lookup("pipe", "uuidgen") }}
      type=wifi
      autoconnect=true
      interface-name={{ item }}
      
      [ipv4]
      method=auto
      
      [ipv6]
      addr-gen-mode=stable-privacy
      method=auto
  loop: "{{ wireless_interfaces }}"

- name: Add all users to group libvirt
  shell: |
    getent passwd | while IFS=: read -r username x uid gid gecos home shell; do
      if [ -n "$home" ] && [ -d "$home" ] && [ "$home" != "/" ]; then
        if [ "$uid" -eq 0 ] || [ "$uid" -ge 1000 ]; then
          echo ":: add $username to group libvirt"
          usermod -a -G libvirt $username
        fi
      fi
    done

- name: Install flatpaks
  shell: |
    # add flathub repo to system
    LC_ALL=C yes | flatpak remote-delete --system flathub
    flatpak remote-add --system flathub {{ setup_facts.setup.flatpak_mirror.flatpakrepo_url | quote }}
    flatpak remotes --columns=name,url
    
    # install firefox as flatpak
    flatpak install -y --noninteractive --system flathub org.mozilla.firefox
    
    # install chromium as flatpak
    flatpak install -y --noninteractive --system flathub org.chromium.Chromium
    
    # install tor browser as flatpak
    flatpak install -y --noninteractive --system flathub org.torproject.torbrowser-launcher

- name: X11 profile fallback
  copy:
    dest: /etc/skel/.xprofile
    mode: 0644
    content: |
      #!/bin/sh
      [ -f ~/.bash_profile ] && . ~/.bash_profile

- name: X11 menu key is super key (for laptops)
  copy:
    dest: /etc/skel/.Xmodmap
    mode: 0644
    content: |
      keysym Menu = Super_R

- name: Prepare firefox flatpak policies
  set_fact:
    firefox_policies:
      policies:
        DontCheckDefaultBrowser: yes
        SkipTermsOfUse: yes
        DisableAppUpdate: yes
        OverrideFirstRunPage: ""
        OverridePostUpdatePage: ""
        ShowHomeButton: yes
        DisableRemoteImprovements: yes
        DisableFirefoxStudies: yes
        Extensions:
          Install:
            - https://addons.mozilla.org/firefox/downloads/latest/adguard-adblocker
            - https://addons.mozilla.org/firefox/downloads/latest/ghostery
            - https://addons.mozilla.org/firefox/downloads/latest/single-file
          Locked:
            - adguardadblocker@adguard.com
            - firefox@ghostery.com
            - "{531906d3-e22f-4a6c-a102-8057b88a1a63}"

- name: Ensure firefox policies folder exists
  file:
    path: /var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/x86_64/stable/policies
    state: directory

- name: Provision firefox flatpak policies
  copy:
    dest: /var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/x86_64/stable/policies/policies.json
    mode: 0644
    content: "{{ firefox_policies | to_json(indent=4, sort_keys=True) }}"

- name: Prepare chromium flatpak policies
  set_fact:
    chromium_adblock:
      BlockThirdPartyCookies: yes
      AdsSettingForIntrusiveAdsSites: 2
      DNSInterceptionChecksEnabled: no
      DnsOverHttpsMode: "off"
    chromium_default_settings:
      ShowHomeButton: yes
      DefaultBrowserSettingEnabled: no
      HardwareAccelerationModeEnabled: yes
      RestoreOnStartup: 1
    chromium_default_extensions:
      ExtensionInstallForcelist:
        - bgnkhhnnamicmpeenaelnjfhikgbkllg;https://clients2.google.com/service/update2/crx
        - mlomiejdfkolichcflejclcbmpeaniij;https://clients2.google.com/service/update2/crx
        - mpiodijhokgodhhofbcjdecpffjipkle;https://clients2.google.com/service/update2/crx
    chromium_telemetry:
      MetricsReportingEnabled: no
      SafeBrowsingProtectionLevel: 0
      AbusiveExperienceInterventionEnforce: no
      GoogleSearchSidePanelEnabled: no
      AdvancedProtectionAllowed: no
      BrowserSignin: 0
    chromium_search_provider:
      DefaultSearchProviderEnabled: yes
      DefaultSearchProviderName: Google
      DefaultSearchProviderSearchURL: "https://google.com/search?sourceid=chrome&q={searchTerms}"
      DefaultSearchProviderSuggestURL: "https://google.com/complete/search?output=chrome&q={searchTerms}"

- name: Ensure chromium policies folder exists
  file:
    path: /var/lib/flatpak/extension/org.chromium.Chromium.Extension.system-policies/x86_64/1/policies/managed
    state: directory

- name: Provision chromium flatpak policies
  copy:
    dest: "/var/lib/flatpak/extension/org.chromium.Chromium.Extension.system-policies/x86_64/1/policies/managed/{{ item.dest }}"
    mode: 0644
    content: "{{ item.var | to_json(indent=4, sort_keys=True) }}"
  loop:
    - dest: adblock.json
      var: "{{ chromium_adblock }}"
    - dest: default-settings.json
      var: "{{ chromium_default_settings }}"
    - dest: default-extensions.json
      var: "{{ chromium_default_extensions }}"
    - dest: telemetry.json
      var: "{{ chromium_telemetry }}"
    - dest: searchprovider.json
      var: "{{ chromium_search_provider }}"

- name: Configure application mime type defaults
  shell: |
    FILELIST=(
      /usr/share/applications/libreoffice-math.desktop
      /usr/share/applications/libreoffice-draw.desktop
      /usr/share/applications/libreoffice-calc.desktop
      /usr/share/applications/libreoffice-writer.desktop
      /usr/share/applications/libreoffice-impress.desktop
      /usr/share/applications/org.kde.konsole.desktop
      /var/lib/flatpak/app/org.mozilla.firefox/current/active/export/share/applications/org.mozilla.firefox.desktop
      /usr/share/applications/engrampa.desktop
      /usr/share/applications/mpv.desktop
      /usr/share/applications/org.kde.kate.desktop
      /usr/share/applications/org.kde.dolphin.desktop
    )
    tee /tmp/mimeapps.list.added <<EOF
    [Added Associations]
    EOF
    tee /tmp/mimeapps.list.default <<EOF
    [Default Applications]
    EOF
    for file in "${FILELIST[@]}"; do
      if [ -f "$file" ]; then
        grep 'MimeType=' "$file" | sed -e 's/.*=//' -e 's/;/\n/g' | while read -r line; do
          if [ -n "$line" ]; then
            # add to existing entry
            if grep -q "$line" /tmp/mimeapps.list.added; then
              sed -i 's|\('"$line"'=.*\)|\1;'"${file##*/}"'|' /tmp/mimeapps.list.added
            else
              tee -a /tmp/mimeapps.list.added <<EOF
    ${line}=${file##*/}
    EOF
            fi
            # overwrite existing entry -> last come, first served
            if grep -q "$line" /tmp/mimeapps.list.default; then
              sed -i 's|'"$line"'=.*|'"$line"'='"${file##*/}"'|' /tmp/mimeapps.list.default
            else
              tee -a /tmp/mimeapps.list.default <<EOF
    ${line}=${file##*/}
    EOF
            fi
          fi
        done
      fi
    done
    cat /tmp/mimeapps.list.added /tmp/mimeapps.list.default > /etc/xdg/mimeapps.list
    rm /tmp/mimeapps.list.added /tmp/mimeapps.list.default

- name: Global xterm fallback to konsole terminal
  shell: |
    ln -s /usr/bin/konsole /usr/local/bin/xterm

- name: Configure global kde shortcuts 1.)
  file:
    path: /etc/skel/.config
    state: directory
    mode: '0755'

- name: Configure global kde shortcuts 2.)
  copy:
    dest: /etc/skel/.config/kglobalshortcutsrc
    mode: 0644
    content: |
      [services][org.kde.konsole.desktop]
      _launch=Ctrl+Alt+T

- name: Configure cups to allow admin group
  shell: |
    sed -i 's|\(SystemGroup .*\)|\1 admins|' /etc/cups/cups-files.conf
