setup:
  distro: archlinux
  options:
    - base
  target: auto
  encrypt:
    enabled: no
    password: packer-build-passwd
    image: devops-linux-archlinux.tar.zst
  ldapauth:
    enabled: no
    authserver: ldap://0.0.0.0/
    base: dc=internal
    group: ou=Groups,dc=internal
    passwd: ou=People,dc=internal
    shadow: ou=People,dc=internal
  archiso_mirror: false
  pkg_mirror: false
  chaotic_mirror: false
distros:
  archlinux: pacman
  debian: apt
  debian-edge: apt
  debian-13: apt
  debian-12: apt
  ubuntu: apt
  ubuntu-edge: apt
  ubuntu-24: apt
  ubuntu-22: apt
  ubuntu-20: apt
  fedora: yum
  fedora-edge: yum
  fedora-42: yum
  rocky: yum
  rocky-edge: yum
  rocky-10: yum
  rocky-9: yum
  rocky-8: yum
download:
  archiso: https://geo.mirror.pkgbuild.com/iso/latest/archlinux-x86_64.iso
  archlinux: https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
  debian: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
  debian-edge: https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-generic-amd64-daily.qcow2
  debian-13: https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-generic-amd64-daily.qcow2
  debian-12: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
  ubuntu: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  ubuntu-edge: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  ubuntu-24: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  ubuntu-22: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  ubuntu-20: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
  fedora: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-UEFI-UKI-42-1.1.x86_64.qcow2
  fedora-edge: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-UEFI-UKI-42-1.1.x86_64.qcow2
  fedora-42: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-UEFI-UKI-42-1.1.x86_64.qcow2
  rocky: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-edge: https://dl.rockylinux.org/pub/rocky/10/images/x86_64/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2
  rocky-10: https://dl.rockylinux.org/pub/rocky/10/images/x86_64/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2
  rocky-9: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-8: https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud.latest.x86_64.qcow2
endoflife:
  debian: https://endoflife.date/api/debian/12.json
  debian-edge: https://endoflife.date/api/debian/13.json
  debian-13: https://endoflife.date/api/debian/13.json
  debian-12: https://endoflife.date/api/debian/12.json
  ubuntu: https://endoflife.date/api/ubuntu/24.04.json
  ubuntu-edge: https://endoflife.date/api/ubuntu/24.04.json
  ubuntu-24: https://endoflife.date/api/ubuntu/24.04.json
  ubuntu-22: https://endoflife.date/api/ubuntu/22.04.json
  ubuntu-20: https://endoflife.date/api/ubuntu/20.04.json
  fedora: https://endoflife.date/api/fedora/42.json
  fedora-edge: https://endoflife.date/api/fedora/42.json
  fedora-42: https://endoflife.date/api/fedora/42.json
  rocky: https://endoflife.date/api/rocky-linux/9.json
  rocky-edge: https://endoflife.date/api/rocky-linux/10.json
  rocky-10: https://endoflife.date/api/rocky-linux/10.json
  rocky-9: https://endoflife.date/api/rocky-linux/9.json
  rocky-8: https://endoflife.date/api/rocky-linux/8.json
images:
  archiso: archlinux-x86_64.iso
  archlinux: Arch-Linux-x86_64-cloudimg.qcow2
  debian: debian-12-generic-amd64.qcow2
  debian-edge: debian-13-generic-amd64-daily.qcow2
  debian-13: debian-13-generic-amd64-daily.qcow2
  debian-12: debian-12-generic-amd64.qcow2
  ubuntu: noble-server-cloudimg-amd64.img
  ubuntu-edge: noble-server-cloudimg-amd64.img
  ubuntu-24: noble-server-cloudimg-amd64.img
  ubuntu-22: jammy-server-cloudimg-amd64.img
  ubuntu-20: focal-server-cloudimg-amd64.img
  fedora: Fedora-Cloud-Base-UEFI-UKI-42-1.1.x86_64.qcow2
  fedora-edge: Fedora-Cloud-Base-UEFI-UKI-42-1.1.x86_64.qcow2
  fedora-42: Fedora-Cloud-Base-UEFI-UKI-42-1.1.x86_64.qcow2
  rocky: Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-edge: Rocky-10-GenericCloud-Base.latest.x86_64.qcow2
  rocky-10: Rocky-10-GenericCloud-Base.latest.x86_64.qcow2
  rocky-9: Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-8: Rocky-8-GenericCloud-Base.latest.x86_64.qcow2
files:
  apt:
    base:
      - path: stage/15_base_system.sh
        stage: 1
    mirror:
      - path: apt/20_localmirror_apt.sh
        stage: 1
    authserver:
      - path: apt/20_authserver_1_apt.sh
        stage: 1
      - path: apt/20_authserver_2_apt.sh
        stage: 2
      - path: apt/20_authserver_apt/rfc2307bis.ldif
        config: true
    kde:
      - path: apt/20_graphical_kde_apt.sh
        stage: 2
    podman:
      - path: apt/20_podman_apt.sh
        stage: 1
      - path: podman/20_portainer_podman.sh
        stage: 2
    postgres:
      - path: podman/40_postgres_podman.sh
        stage: 2
    homeassistant:
      - path: podman/40_homeassistant_podman.sh
        stage: 2
    cronicle:
      - path: podman/40_cronicle_podman.sh
        stage: 2
    dagu:
      - path: podman/40_dagu_podman.sh
        stage: 2
    nextcloud:
      - path: podman/40_nextcloud_podman.sh
        stage: 2
    plex:
      - path: podman/40_plex_podman.sh
        stage: 2
    jellyfin:
      - path: podman/40_jellyfin_podman.sh
        stage: 2
    minecraft-cobblemon:
      - path: podman/40_minecraft_cobblemon_podman.sh
        stage: 2
    minecraft-create:
      - path: podman/40_minecraft_create_podman.sh
        stage: 2
    cicd:
      - path: podman/60_cicd_podman.sh
        stage: 2
    gitlab:
      - path: podman/40_gitlab_podman.sh
        stage: 2
    proxmox:
      - path: apt/20_proxmox_1_apt.sh
        stage: 1
      - path: apt/20_proxmox_2_apt.sh
        stage: 2
    proxmox-devops:
      - path: apt/30_proxmox_3_apt.sh
        stage: 2
    router:
      - path: apt/20_router_apt.sh
        stage: 2
      - path: apt/20_router_apt/pxelinux.cfg.default
        config: true
    podman-image:
      - path: podman/90_podman_image.sh
        stage: 2
    pxe-image:
      - path: pxe/90_pxe_image.sh
        stage: 2
      - path: pxe/90_pxe_image/apt/hook
        config: true
      - path: pxe/90_pxe_image/apt/modules
        config: true
      - path: pxe/90_pxe_image/apt/pxe
        config: true
      - path: pxe/90_pxe_image/apt/pxe-http
        config: true
      - path: pxe/90_pxe_image/apt/pxe-nfs
        config: true
      - path: pxe/90_pxe_image/apt/pxe-cifs
        config: true
    tar-image:
      - path: tar/90_tar_image.sh
        stage: 2
    hardening:
      - path: audit/70_hardening.sh
        stage: 2
    audit:
      - path: audit/80_lynis.sh
        stage: 2
  pacman:
    base:
      - path: stage/15_base_system.sh
        stage: 1
    mirror:
      - path: pacman/20_localmirror_pacman.sh
        stage: 1
    authserver:
      - path: pacman/20_authserver_1_pacman.sh
        stage: 1
      - path: pacman/20_authserver_2_pacman.sh
        stage: 2
      - path: pacman/20_authserver_pacman/rfc2307bis.ldif
        config: true
    cinnamon:
      - path: pacman/20_graphical_cinnamon_pacman.sh
        stage: 2
    kde:
      - path: pacman/20_graphical_kde_pacman.sh
        stage: 2
    cosmic:
      - path: pacman/20_graphical_cosmic_pacman.sh
        stage: 2
    podman:
      - path: pacman/20_podman_pacman.sh
        stage: 1
      - path: podman/20_portainer_podman.sh
        stage: 2
    postgres:
      - path: podman/40_postgres_podman.sh
        stage: 2
    homeassistant:
      - path: podman/40_homeassistant_podman.sh
        stage: 2
    cronicle:
      - path: podman/40_cronicle_podman.sh
        stage: 2
    dagu:
      - path: podman/40_dagu_podman.sh
        stage: 2
    nextcloud:
      - path: podman/40_nextcloud_podman.sh
        stage: 2
    plex:
      - path: podman/40_plex_podman.sh
        stage: 2
    jellyfin:
      - path: podman/40_jellyfin_podman.sh
        stage: 2
    minecraft-cobblemon:
      - path: podman/40_minecraft_cobblemon_podman.sh
        stage: 2
    minecraft-create:
      - path: podman/40_minecraft_create_podman.sh
        stage: 2
    cicd:
      - path: podman/60_cicd_podman.sh
        stage: 2
    gitlab:
      - path: podman/40_gitlab_podman.sh
        stage: 2
    router:
      - path: pacman/20_router_pacman.sh
        stage: 2
      - path: pacman/20_router_pacman/pxelinux.cfg.default
        config: true
    podman-image:
      - path: podman/90_podman_image.sh
        stage: 2
    pxe-image:
      - path: pxe/90_pxe_image.sh
        stage: 2
      - path: pxe/90_pxe_image/hooks/pxe
        config: true
      - path: pxe/90_pxe_image/hooks/pxe_cifs
        config: true
      - path: pxe/90_pxe_image/hooks/pxe_http
        config: true
      - path: pxe/90_pxe_image/hooks/pxe_iscsi
        config: true
      - path: pxe/90_pxe_image/hooks/pxe_nbd
        config: true
      - path: pxe/90_pxe_image/hooks/pxe_nfs
        config: true
      - path: pxe/90_pxe_image/hooks/pxe_nvmeof
        config: true
      - path: pxe/90_pxe_image/hooks/pxe_scp
        config: true
      - path: pxe/90_pxe_image/hooks/pxe_wg
        config: true
      - path: pxe/90_pxe_image/install/pxe
        config: true
      - path: pxe/90_pxe_image/install/pxe_cifs
        config: true
      - path: pxe/90_pxe_image/install/pxe_http
        config: true
      - path: pxe/90_pxe_image/install/pxe_iscsi
        config: true
      - path: pxe/90_pxe_image/install/pxe_nbd
        config: true
      - path: pxe/90_pxe_image/install/pxe_nfs
        config: true
      - path: pxe/90_pxe_image/install/pxe_nvmeof
        config: true
      - path: pxe/90_pxe_image/install/pxe_scp
        config: true
      - path: pxe/90_pxe_image/install/pxe_wg
        config: true
      - path: pxe/90_pxe_image/pxe.conf
        config: true
      - path: pxe/90_pxe_image/pxe.preset
        config: true
    tar-image:
      - path: tar/90_tar_image.sh
        stage: 2
    archiso-disc:
      - path: pacman/90_archiso_disc.sh
        stage: 2
    hardening:
      - path: audit/70_hardening.sh
        stage: 2
    audit:
      - path: audit/80_lynis.sh
        stage: 2
  yum:
    base:
      - path: stage/15_base_system.sh
        stage: 1
    mirror:
      - path: yum/20_localmirror_yum.sh
        stage: 1
    hardening:
      - path: audit/70_hardening.sh
        stage: 2
    audit:
      - path: audit/80_lynis.sh
        stage: 2
