distros:
  archlinux: pacman
  debian: apt
  debian-12: apt
  ubuntu: apt
  ubuntu-24: apt
  ubuntu-22: apt
  ubuntu-20: apt
  rocky: yum
  rocky-9: yum
  rocky-8: yum
download:
  archiso: https://geo.mirror.pkgbuild.com/iso/latest/archlinux-x86_64.iso
  archlinux: https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
  debian: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
  debian-12: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
  ubuntu: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  ubuntu-24: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  ubuntu-22: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  ubuntu-20: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
  rocky: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-9: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-8: https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud.latest.x86_64.qcow2
endoflife:
  debian: https://endoflife.date/api/debian/12.json
  debian-12: https://endoflife.date/api/debian/12.json
  ubuntu: https://endoflife.date/api/ubuntu/24.04.json
  ubuntu-24: https://endoflife.date/api/ubuntu/24.04.json
  ubuntu-22: https://endoflife.date/api/ubuntu/22.04.json
  ubuntu-20: https://endoflife.date/api/ubuntu/20.04.json
  rocky: https://endoflife.date/api/rocky-linux/9.json
  rocky-9: https://endoflife.date/api/rocky-linux/9.json
  rocky-8: https://endoflife.date/api/rocky-linux/8.json
images:
  archiso: archlinux-x86_64.iso
  archlinux: Arch-Linux-x86_64-cloudimg.qcow2
  debian: debian-12-generic-amd64.qcow2
  debian-12: debian-12-generic-amd64.qcow2
  ubuntu: noble-server-cloudimg-amd64.img
  ubuntu-24: noble-server-cloudimg-amd64.img
  ubuntu-22: jammy-server-cloudimg-amd64.img
  ubuntu-20: focal-server-cloudimg-amd64.img
  rocky: Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-9: Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  rocky-8: Rocky-8-GenericCloud-Base.latest.x86_64.qcow2
files:
  apt:
    base:
      - path: stage/15_base_system.sh
        stage: 1
    mirror:
      - path: apt/20_localmirror_apt.sh
        stage: 1
    proxmox:
      - path: apt/20_proxmox_1_apt.sh
        stage: 1
      - path: apt/20_proxmox_2_apt.sh
        stage: 2
  pacman:
    base:
      - path: stage/15_base_system.sh
        stage: 1
    mirror:
      - path: pacman/20_localmirror_pacman.sh
        stage: 1
    cinnamon:
      - path: pacman/20_graphical_cinnamon_pacman.sh
        stage: 1
    kde:
      - path: pacman/20_graphical_kde_pacman.sh
        stage: 1
    router:
      - path: pacman/20_router_pacman.sh
        stage: 1
    podman-image:
      - path: pacman/ZZ_podman_image.sh
        stage: 2
    pxe-image:
      - path: pacman/ZZ_pxe_image.sh
        stage: 2
  yum:
    base:
      - path: stage/15_base_system.sh
        stage: 1
    mirror:
      - path: yum/20_localmirror_yum.sh
        stage: 1
setup:
  distro: archlinux
  options:
    - base
  env_vars: []
  target: /dev/vda
  archiso_mirror: false
  pkg_mirror: false
  chaotic_mirror: false
