#!/usr/bin/ash

run_hook() {
    if [ -n "${ip}" ] && [ -n "${pxe_iso_srv}" ]; then
        # copy to RAM logic is disabled, as the image will be downloaded to RAM
        export copytoram="n"

        pxe_iso_srv=$(eval echo "${pxe_iso_srv}")

        # enable chained http mount handler
        export mount_handler="pxe_iso_mount_handler"
    fi
}

# args: /path/to/newroot
pxe_iso_mount_handler() {
    newroot="${1}"
    local http_iso="${pxe_iso_srv}"
    # append default iso path if no iso file was given
    if [ "${pxe_iso_srv//.iso}" == "${pxe_iso_srv}" ]; then
        http_iso="${pxe_iso_srv%/}/archlinux-x86_64.iso"
    fi

    msg ":: Boot ArchISO using PXE"

    # 1st: check the copy to RAM filesystem is present
    if ! mountpoint -q "${copytoram_mnt}"; then
        msg ":: Mount ${copytoram_mnt} (tmpfs) filesystem, size=${copytoram_size}"
        mount --mkdir -t tmpfs -o "size=${copytoram_size}",mode=0755 copytoram "${copytoram_mnt}"
    fi

    local local_iso="${copytoram_mnt}/archlinux-x86_64.iso"

    # 2nd: download the iso
    msg ":: Download '${http_iso}' to '${local_iso}'"
    if ! wget -c -O "${local_iso}" "${http_iso}"; then
        echo "!! ERROR: could not download '${http_iso}' to '${local_iso}'"
        launch_interactive_shell
    fi

    local iso_mnt="/run/pxe/iso"

    # 3rd: loopback mount the iso
    msg ":: Loopback mount the ISO '${local_iso}'"
    if ! mount --mkdir -o loop "${local_iso}" "${iso_mnt}"; then
        echo "!! ERROR: could not loopback mount '${local_iso}' to '${iso_mnt}'"
        launch_interactive_shell
    fi
    
    local local_img="${copytoram_mnt}/arch/${arch}/pxeboot.img"

    # 4th: symlink the containing airootfs to the correct location
    msg ":: symlink the containing airootfs to the correct location"
    mkdir -p "${local_img%/pxeboot.img}"
    if [ -f "${iso_mnt}/arch/x86_64/airootfs.sfs" ]; then
        ln -s "${iso_mnt}/arch/x86_64/airootfs.sfs" "${local_img}"
    elif [ -f "${iso_mnt}/arch/x86_64/airootfs.erofs" ]; then
        ln -s "${iso_mnt}/arch/x86_64/airootfs.erofs" "${local_img}"
    else
        echo "!! ERROR: '${iso_mnt}' (${http_iso}) is no standard ArchISO format"
        launch_interactive_shell
    fi

    # 5th: create the boot mount point for pxe_mount_handler with correct image placement
    msg ":: Bindmount '${copytoram_mnt}' as '${boot_mnt}'"
    if ! mount --mkdir -o bind "${copytoram_mnt}" "${boot_mnt}"; then
        echo "!! ERROR: failed to mount '${copytoram_mnt}'"
        launch_interactive_shell
    fi

    pxe_mount_handler "${newroot}"
}
