#!/bin/sh -e

pxe_iso_hook() {
    # parse kernel cmdline args
    for x in $(cat /proc/cmdline); do
        case $x in
            pxe_iso_srv=*)
                export pxe_iso_srv=${x#pxe_iso_srv=}
                ;;
            pxe_iso_path=*)
                export pxe_iso_path=${x#pxe_iso_path=}
                ;;
            pxe_nfs_opt=*)
                export pxe_nfs_opt=${x#pxe_nfs_opt=}
                ;;
        esac
    done

    if [ -n "${ip}" ] && [ -n "${pxe_iso_srv}" ]; then
        modprobe nfs 2>/dev/null
        modprobe sunrpc 2>/dev/null

        export pxe_iso_srv=$(eval echo "${pxe_iso_srv}")

        pxe_iso_mount_handler
    fi
}

pxe_iso_mount_handler() {
    echo ":: Boot ArchISO using PXE and NFS"

    local local_nfs_mnt="/run/pxe/nfsmnt"

    # 1st: mount the nfs root
    echo ":: Mount NFS share '${pxe_iso_srv}'"
    mkdir -p "${local_nfs_mnt}"
    local mount_status
    echo ":: trying nfs 4"
    if [ -n "${pxe_nfs_opt}" ]; then
        timeout 15 mount.nfs4 -o "${pxe_nfs_opt}" "${pxe_iso_srv}" "${local_nfs_mnt}"
    else
        timeout 15 mount.nfs4 "${pxe_iso_srv}" "${local_nfs_mnt}"
    fi
    mount_status=$?
    if [ "$mount_status" -gt 0 ]; then
        echo ":: trying nfs 3"
        if [ -n "${pxe_nfs_opt}" ]; then
            timeout 15 nfsmount -o "${pxe_nfs_opt}" "${pxe_iso_srv}" "${local_nfs_mnt}"
        else
            timeout 15 nfsmount "${pxe_iso_srv}" "${local_nfs_mnt}"
        fi
        mount_status=$?
    fi
    if [ "$mount_status" -gt 0 ]; then
        panic "!! ERROR: failed to mount '${local_nfs_mnt}'"
    fi

    # 2nd: check the copy to RAM filesystem is present
    if ! mountpoint -q "${copytoram_mnt}"; then
        echo ":: Mount ${copytoram_mnt} (tmpfs) filesystem, size=${copytoram_size}"
        mkdir -p "${copytoram_mnt}"
        mount -t tmpfs -o "size=${copytoram_size}",mode=0755 copytoram "${copytoram_mnt}"
    fi

    local iso_path="${local_nfs_mnt%/}/${pxe_iso_path}"
    local local_iso_mnt="/run/pxe/isomnt"

    # 3rd: loopback mount the iso
    echo ":: Loopback mount the ISO '${iso_path}'"
    mkdir -p "${local_iso_mnt}"
    if ! mount -t iso9660 -o loop "${iso_path}" "${local_iso_mnt}"; then
        panic "!! ERROR: could not loopback mount '${iso_path}' to '${local_iso_mnt}'"
    fi

    local local_img="${copytoram_mnt}/${dist}/${arch}/pxeboot.img"

    # 4th: symlink the containing airootfs to the correct location
    echo ":: Wait for ISO device"
    matched=""
    while [ -z "${matched}" ]; do
        for i in "${local_iso_mnt}/live"/*; do
            if [ "${i%.squashfs}" != "${i}" ]; then
                matched="${i}"
                break
            fi
        done
        echo ":: ..."
        sleep 2
    done
    echo ":: Symlink '${matched}' to '${local_img}'"
    mkdir -p "${local_img%/pxeboot.img}"
    ln -s "${matched}" "${local_img}"

    # 5th: create the boot mount point for pxe_mount_handler with correct image placement
    echo ":: Bindmount '${copytoram_mnt}' as '${boot_mnt}'"
    mkdir -p "${boot_mnt}"
    if ! mount -o bind "${copytoram_mnt}" "${boot_mnt}"; then
        panic "!! ERROR: failed to mount '${copytoram_mnt}'"
    fi
}
