#!/usr/bin/env bash

build() {
    add_module "nfs"
    add_module "sunrpc"

    add_runscript

    add_binary timeout
    add_binary /usr/lib/initcpio/nfsmount /usr/bin/nfsmount
    add_binary mount.nfs4
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for boot via PXE and NFS.
HELPEOF
}
