#!/usr/bin/env bash

build() {
    add_runscript

    if command -v wget >/dev/null 2>&1; then
        add_binary wget
    else
        warning 'wget not found; falling back to curl'
        add_binary curl
    fi

    add_file /etc/ssl/certs/ca-certificates.crt
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for boot via PXE and HTTP.
HELPEOF
}
